include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    constant_identifier_names: ignore
    lines_longer_than_80_chars: ignore
    non_constant_identifier_names: ignore
  exclude:
    - build/**
linter:
  rules:
    file_names: false
